# Site settings
title: BYFC
subtitle: Tournament 2017
email: webmaster@barmingyouth.co.uk
description: To find your way around click on Get Started<br /> Use the menu (top right) to view results.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 40 Bridge Mill Way
city: Maidstone
state: Kent
zip_code: ME15 6FD
country: 
phone: 07710 425812

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url: https://www.facebook.com/BYFCTournament
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/BarmingYouthFC

# Build settings
markdown: kramdown

sass:
  style: compressed
